# Generated by Django 4.1.1 on 2023-01-12 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='applymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compnm', models.CharField(max_length=50)),
                ('jobtitle', models.CharField(max_length=50)),
                ('empname', models.CharField(max_length=50)),
                ('empemail', models.EmailField(max_length=254)),
                ('empph', models.IntegerField()),
                ('exp', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='modelempreg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('quali', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='postjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('jtitle', models.CharField(max_length=50)),
                ('wtype', models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid')], max_length=30)),
                ('expreq', models.CharField(choices=[('0 - 1', '0 - 1'), ('1 - 2', '1 - 2'), ('2 - 3', '2 - 3'), ('3 - 4', '3 - 4'), ('4 - 5', '4 - 5'), ('5 - 6', '5 - 6'), ('6 - 7', '6 - 7'), ('7 - 8', '7 - 8')], max_length=30)),
                ('jtype', models.CharField(choices=[('parttime', 'parttime'), ('fulltime', 'fulltime')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
